### ISSUE TITLE
Compression keeps running

### ISSUE THREAD

**Issue by wouterverstuyf** [friends-of-forkcms/fork-cms-module-compression#8]
In the newest Fork version (5.8.0) the compression action keeps running, in the console you can see the "File read" is counting but none of the images are being compressed.
A time out is the result.

Already did some debugging and found 1 fix that helped a little bit but after compressing a few images the process again keeps running.

/Engine/TinyPNGApi.php - Line 108
if (substr($header, 0, 10) === 'Location: ') {

By dumping the $header it seems the "Location: ' is lower case 'location: '

**Comment by jessedobbelaere** [comment]
Interesting find 👀 !

I have a WIP version that uses the latest composer package for the TinyPNG api, with Server-Sent Events (SSE) to push realtime feedback to the console, will try to finish that and publish a branch. Might fix this issue as the TinyPNGApi.php has not been updated in a while in this repo

**Comment by wouterverstuyf** [comment]
@jessedobbelaere  thx, would be great! My first thought was indeed an outdated TinyPNGApi.php

**Comment by jessedobbelaere** [comment]
@wouterverstuyf I had issues in my branch too using the `tinify/tinify` library where it stalls (request to tinypng does not get a response back) 😕 Could be related to the issue you have. Not sure yet what the root cause is...

However, I got compression working using a different library (https://github.com/robopuff/tinypng) but it lacks a way to check how many credits you have left. So what I plan to do is add my own simple Guzzle client in the module that can send a file for compression, or just ask for credits left... 


FYI I linked the draft MR of v4.0.0 to this issue, if you're curious :-) Tried to use some cool tech like React and SSE events in the new version

**Comment by wouterverstuyf** [comment]
@jessedobbelaere Great, thx for your time! Glad that this will be solved :)

**Comment by jessedobbelaere** [comment]
Can you try v4.0.0? I tested this on one of my websites and seems to be working okay :D 
https://github.com/friends-of-forkcms/fork-cms-module-compression/releases/tag/4.0.0
